const assert = require("node:assert/strict");
const test = require("node:test");

const {
  buildHeuristicValidation,
  refineGroqAnalysis,
} = require("../text-heuristic-validation");

const baseValidated = {
  emotion: "Neutral",
  sentiment: 50,
  stress: 20,
  risk: "Low",
  support: "Gentle check-in",
  response: "x",
  recommendations: [],
  emotionSignals: {
    calm: 0,
    joy: 0,
    hopeful: 0,
    focused: 0,
    neutral: 1,
    fatigue: 0,
    sadness: 0,
    anxiety: 0,
    stress: 0,
    anger: 0,
    fear: 0,
    overwhelm: 0,
  },
  primaryEmotionKey: "neutral",
};

const cases = [
  {
    text: "I feel drained, anxious, and mentally overloaded today.",
    build: {
      confidence: 91,
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0, fatigue: 0.3222, sadness: 0, anxiety: 0.4027, stress: 0.1457, anger: 0, fear: 0, overwhelm: 0.1294 },
      evidence: { calm: 0, joy: 0, hopeful: 0, focused: 0, fatigue: 0.6, sadness: 0, anxiety: 0.75, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      inferredRisk: "High",
      negativeHits: 0,
      positiveHits: 0,
      primaryEmotionKey: "anxiety",
      sentiment: 47,
      stress: 33,
      topEvidenceScore: 0.75,
    },
    refine: {
      emotion: "Anxiety",
      sentiment: 50,
      stress: 33,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0.0485, fatigue: 0.3636, sadness: 0, anxiety: 0.4545, stress: 0.0706, anger: 0, fear: 0, overwhelm: 0.0627 },
      primaryEmotionKey: "anxiety",
    },
  },
  {
    text: "I feel disconnected, tired, and low on motivation.",
    build: {
      confidence: 100,
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0.0462, neutral: 0, fatigue: 0.4238, sadness: 0.4026, anxiety: 0.1274, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      evidence: { calm: 0, joy: 0, hopeful: 0, focused: 0, fatigue: 1, sadness: 0.95, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      inferredRisk: "Moderate",
      negativeHits: 1,
      positiveHits: 0,
      primaryEmotionKey: "fatigue",
      sentiment: 36,
      stress: 19,
      topEvidenceScore: 1,
    },
    refine: {
      emotion: "Fatigue",
      sentiment: 50,
      stress: 20,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0.017, neutral: 0.0369, fatigue: 0.4611, sadness: 0.438, anxiety: 0.047, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      primaryEmotionKey: "fatigue",
    },
  },
  {
    text: "I feel okay overall, but I need help staying calm and focused.",
    build: {
      confidence: 99,
      emotionSignals: { calm: 0.3555, joy: 0, hopeful: 0, focused: 0.3809, neutral: 0.2635, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      evidence: { calm: 0.7, joy: 0, hopeful: 0, focused: 0.75, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      inferredRisk: "Low",
      negativeHits: 0,
      positiveHits: 3,
      primaryEmotionKey: "focused",
      sentiment: 81,
      stress: 6,
      topEvidenceScore: 0.75,
    },
    refine: {
      emotion: "Focused",
      sentiment: 72,
      stress: 20,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0.4575, joy: 0, hopeful: 0, focused: 0.4902, neutral: 0.0523, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      primaryEmotionKey: "focused",
    },
  },
  {
    text: "I have been feeling overwhelmed with classes and deadlines. I am tired, anxious, and finding it hard to switch off my thoughts at night.",
    build: {
      confidence: 100,
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0, fatigue: 0.2376, sadness: 0, anxiety: 0.324, stress: 0.0928, anger: 0, fear: 0, overwhelm: 0.3456 },
      evidence: { calm: 0, joy: 0, hopeful: 0, focused: 0, fatigue: 0.55, sadness: 0, anxiety: 0.75, stress: 0, anger: 0, fear: 0, overwhelm: 0.8 },
      inferredRisk: "High",
      negativeHits: 2,
      positiveHits: 0,
      primaryEmotionKey: "overwhelm",
      sentiment: 19,
      stress: 67,
      topEvidenceScore: 0.8,
    },
    refine: {
      emotion: "Overwhelm",
      sentiment: 41,
      stress: 55,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0.0355, fatigue: 0.244, sadness: 0, anxiety: 0.3327, stress: 0.0329, anger: 0, fear: 0, overwhelm: 0.3549 },
      primaryEmotionKey: "overwhelm",
    },
  },
  {
    text: "I am happy, proud, and excited about the progress I made today.",
    build: {
      confidence: 100,
      emotionSignals: { calm: 0, joy: 0.7156, hopeful: 0.2844, focused: 0, neutral: 0, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      evidence: { calm: 0, joy: 1, hopeful: 0, focused: 0, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      inferredRisk: "Low",
      negativeHits: 0,
      positiveHits: 1,
      primaryEmotionKey: "joy",
      sentiment: 74,
      stress: 11,
      topEvidenceScore: 1,
    },
    refine: {
      emotion: "Joy",
      sentiment: 82,
      stress: 20,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0, joy: 0.7648, hopeful: 0.174, focused: 0, neutral: 0.0612, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      primaryEmotionKey: "joy",
    },
  },
  {
    text: "I feel calm, grounded, and peaceful after taking a short break.",
    build: {
      confidence: 100,
      emotionSignals: { calm: 1, joy: 0, hopeful: 0, focused: 0, neutral: 0, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      evidence: { calm: 1, joy: 0, hopeful: 0, focused: 0, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      inferredRisk: "Low",
      negativeHits: 0,
      positiveHits: 2,
      primaryEmotionKey: "calm",
      sentiment: 87,
      stress: 5,
      topEvidenceScore: 1,
    },
    refine: {
      emotion: "Calm",
      sentiment: 82,
      stress: 20,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0.9259, joy: 0, hopeful: 0, focused: 0, neutral: 0.0741, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      primaryEmotionKey: "calm",
    },
  },
  {
    text: "I am frustrated and angry because everything feels unfair right now.",
    build: {
      confidence: 100,
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 1, fear: 0, overwhelm: 0 },
      evidence: { calm: 0, joy: 0, hopeful: 0, focused: 0, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 1, fear: 0, overwhelm: 0 },
      inferredRisk: "Moderate",
      negativeHits: 1,
      positiveHits: 0,
      primaryEmotionKey: "anger",
      sentiment: 29,
      stress: 31,
      topEvidenceScore: 1,
    },
    refine: {
      emotion: "Anger",
      sentiment: 45,
      stress: 31,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0.0741, fatigue: 0, sadness: 0, anxiety: 0, stress: 0, anger: 0.9259, fear: 0, overwhelm: 0 },
      primaryEmotionKey: "anger",
    },
  },
  {
    text: "I feel hopeless and worthless and I cannot cope with this pressure.",
    build: {
      confidence: 100,
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0, fatigue: 0, sadness: 0.4348, anxiety: 0, stress: 0.2391, anger: 0, fear: 0, overwhelm: 0.3261 },
      evidence: { calm: 0, joy: 0, hopeful: 0, focused: 0, fatigue: 0, sadness: 1, anxiety: 0, stress: 0.55, anger: 0, fear: 0, overwhelm: 0.75 },
      inferredRisk: "High",
      negativeHits: 2,
      positiveHits: 1,
      primaryEmotionKey: "sadness",
      sentiment: 4,
      stress: 100,
      topEvidenceScore: 1,
    },
    refine: {
      emotion: "Sadness",
      sentiment: 37,
      stress: 55,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0.0336, fatigue: 0, sadness: 0.4202, anxiety: 0, stress: 0.2311, anger: 0, fear: 0, overwhelm: 0.3151 },
      primaryEmotionKey: "sadness",
    },
  },
  {
    text: "I am nervous and worried with racing thoughts before my exam.",
    build: {
      confidence: 100,
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0, fatigue: 0, sadness: 0, anxiety: 1, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      evidence: { calm: 0, joy: 0, hopeful: 0, focused: 0, fatigue: 0, sadness: 0, anxiety: 1, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      inferredRisk: "Moderate",
      negativeHits: 1,
      positiveHits: 0,
      primaryEmotionKey: "anxiety",
      sentiment: 24,
      stress: 37,
      topEvidenceScore: 1,
    },
    refine: {
      emotion: "Anxiety",
      sentiment: 45,
      stress: 37,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0, neutral: 0.0741, fatigue: 0, sadness: 0, anxiety: 0.9259, stress: 0, anger: 0, fear: 0, overwhelm: 0 },
      primaryEmotionKey: "anxiety",
    },
  },
  {
    text: "I feel productive, focused, and organized, but a little tense about deadlines.",
    build: {
      confidence: 100,
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0.6452, neutral: 0, fatigue: 0, sadness: 0, anxiety: 0, stress: 0.3548, anger: 0, fear: 0, overwhelm: 0 },
      evidence: { calm: 0, joy: 0, hopeful: 0, focused: 1, fatigue: 0, sadness: 0, anxiety: 0, stress: 0.55, anger: 0, fear: 0, overwhelm: 0 },
      inferredRisk: "Low",
      negativeHits: 1,
      positiveHits: 1,
      primaryEmotionKey: "focused",
      sentiment: 49,
      stress: 25,
      topEvidenceScore: 1,
    },
    refine: {
      emotion: "Focused",
      sentiment: 72,
      stress: 20,
      risk: "Low",
      support: "Gentle check-in",
      response: "x",
      recommendations: [],
      emotionSignals: { calm: 0, joy: 0, hopeful: 0, focused: 0.6135, neutral: 0.0491, fatigue: 0, sadness: 0, anxiety: 0, stress: 0.3374, anger: 0, fear: 0, overwhelm: 0 },
      primaryEmotionKey: "focused",
    },
  },
];

test("buildHeuristicValidation snapshots representative text inputs", () => {
  cases.forEach(({ text, build }) => {
    assert.deepEqual(buildHeuristicValidation(text), build, text);
  });
});

test("refineGroqAnalysis snapshots representative text inputs", () => {
  cases.forEach(({ text, refine }) => {
    assert.deepEqual(refineGroqAnalysis(baseValidated, text), refine, text);
  });
});
